Split content and provide example for externaldb
cloudfoundry-incubator/kubecf-docs pull request #35
Opened 2020-10-08 14:40 UTC by mudler

2020-10-08 16:45 UTC, mook-as requested changes
I see that we have some duplicate content; a similar section is under [minikube docs](https://kubecf.io/docs/tutorials/deploy-minikube/#advanced-topics); perhaps we should make that point this way as well?

2020-10-08 16:45 UTC, mook-as commented on content/en/docs/Deployment/kubernetes-deploy.md
>  > The above `helm install` will generate many controllers spread over multiple pods inside the `cfo`
```suggestion
> The above `helm install` will generate many controllers spread over multiple pods inside the `cf-operator`
```

I realize you didn't change this, but still… it was wrong :)

2020-10-08 16:45 UTC, mook-as commented on content/en/docs/Deployment/kubernetes-deploy.md
> +{{% alert title="Also" %}}
```suggestion
{{% alert title="Note" %}}
```
Having a section titled `Also` is kind of odd; just repeating it instead should be fine (given that it's just a callout, not a section header in the ToC).

2020-10-08 16:45 UTC, mook-as commented on content/en/docs/Deployment/kubernetes-deploy.md
> +> How the namespace the operator is installed into (`cfo`) differs from the namespace the operator
```suggestion
> How the namespace the operator is installed into (`cf-operator`) differs from the namespace the operator
```

2020-10-08 16:45 UTC, mook-as commented on content/en/docs/Deployment/kubernetes-deploy.md
> +See [Advanced Topics](/docs/deployment/advanced-topics) for more configuration settings available in KubeCF
```suggestion
See [Advanced Topics](/docs/deployment/advanced-topics) for more configuration settings available in KubeCF.
```

2020-10-09 12:40 UTC, mudler commented on content/en/docs/Deployment/advanced-topics.md
> +applications. Eirini is an alternative to Diego that follows a more
:+1: Fixed in https://github.com/cloudfoundry-incubator/kubecf-docs/pull/35/commits/353d9bf2a5e01ae713f8398347c5df95eeba11b0

2020-10-09 12:41 UTC, merged